### PR TITLE
Test on Python 3.7-dev

### PR DESCRIPTION
**Pull request by hugovk**
Note: Python 3.7 currently fails.

There's a fix coming in https://github.com/pika/pika/pull/924.

### CODE REVIEW

**Comment by lukebakken** [comment]
Looks like the failure is not what #924 fixes -

```
Collecting pyev
  Downloading pyev-0.9.0.tar.gz (223kB)
    100% |████████████████████████████████| 225kB 2.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ujxp2ys6/pyev/setup.py", line 56, in <module>
        check_version(python_version, min_python_versions[major], "Python{0}".format(major))
      File "/tmp/pip-build-ujxp2ys6/pyev/setup.py", line 40, in check_version
        if StrictVersion(current_version) < StrictVersion(minimum_version):
      File "/opt/python/3.7-dev/lib/python3.7/distutils/version.py", line 40, in __init__
        self.parse(vstring)
      File "/opt/python/3.7-dev/lib/python3.7/distutils/version.py", line 137, in parse
        raise ValueError("invalid version number '%s'" % vstring)
    ValueError: invalid version number '3.7.0a4+'
```

**Comment by michaelklishin** [comment]
I'm hardly a Python expert but looks like `distutils` version parser does not expect the version this 3.7 package uses?

**Comment by hugovk** [comment]
I think the problem is in pyev, it compares two StrictVersions, which don't work with the 3.7 dev version. Something like LooseVersion might work. 

The last pyev release is this 0.9.0, from 2013.

**Comment by lukebakken** [comment]
We may want to consider dropping `pyev` support since it is basically unmaintained. @gmr what do you think?

**Comment by gmr** [comment]
I'm fine with that. I've got a pattern of use with travis that works pretty good for collective coverage now too. I'll submit a PR that cleans up  travis and removes pyenv.

**Comment by lukebakken** [comment]
We'll get this once #937 is merged.

**Comment by hugovk** [comment]
Rebased, and now PyYAML fails to build on 3.7: 

```
  ext/_yaml.c: In function ‘__Pyx__ExceptionSave’:
  ext/_yaml.c:24143:19: error: ‘PyThreadState’ has no member named ‘exc_type’
       *type = tstate->exc_type;
                     ^
  ext/_yaml.c:24144:20: error: ‘PyThreadState’ has no member named ‘exc_value’
       *value = tstate->exc_value;
                      ^
  ext/_yaml.c:24145:17: error: ‘PyThreadState’ has no member named ‘exc_traceback’
       *tb = tstate->exc_traceback;
                   ^
  ext/_yaml.c: In function ‘__Pyx__ExceptionReset’:
  ext/_yaml.c:24152:22: error: ‘PyThreadState’ has no member named ‘exc_type’
     member named ‘exc_traceback’
       tstate->exc_traceback = local_tb;
             ^
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for PyYAML
  Running setup.py clean for PyYAML
Failed to build PyYAML
```

https://travis-ci.org/pika/pika/jobs/335516418

**Comment by hugovk** [comment]
I've reported this to PyYAML: https://github.com/yaml/pyyaml/issues/126.

**Comment by lukebakken** [comment]
@hugovk looks like pinning `awscli` to version `1.11.18` could work. Waiting on builds now.

**Comment by lukebakken** [comment]
Well, `3.7.-dev` is fixed, but now there's this - @gmr is this due to the older `awscli` version?

```
$ aws s3 cp --recursive s3://com-gavinroy-travis/pika/$TRAVIS_BUILD_NUMBER/ coverage
fatal error: Unable to locate credentials
The command "aws s3 cp --recursive s3://com-gavinroy-travis/pika/$TRAVIS_BUILD_NUMBER/ coverage" exited with 1.
```

**Comment by hugovk** [comment]
@lukebakken That'll be https://github.com/pika/pika/pull/937#issuecomment-361953868.

**Comment by hugovk** [comment]
Good news, PyYAML 4.1 has just been released which now supports Python 3.7: https://github.com/yaml/pyyaml/issues/126.

When https://github.com/aws/aws-cli/pull/3414 is merged to upgrade the PyYAML used by awscli, the awscli version pinning from this PR can be removed.
