### PR TITLE
Fix examples for new API

### PR DESCRIPTION
**Pull request by claws**
The asynchronous consumer example does not work in the current master branch.

I installed the ``pika`` Python project after downloading the current master from Github.
``` console
(venv) $ python
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pika
>>> pika.__version__
'1.0.0b1'
```

After starting an RabbitMQ server I then tried to run the examples ``asynchronous_consumer_example.py`` and ``asynchronous_publisher_example.py`` where I encountered errors that stopped the consumer from running. A snippet of the error is shown below.

``` python
Traceback (most recent call last):
  File "/path/to/my/venv/lib/python3.6/site-packages/pika/adapters/utils/io_services_utils.py", line 1037, in _on_socket_readable
    self._consume()
  File "/path/to/my/venv/lib/python3.6/site-packages/pika/adapters/utils/io_services_utils.py", line 796, in _consume
    self._protocol.data_received(data)
  File "/path/to/my/venv/lib/python3.6/site-packages/pika/adapters/base_connection.py", line 492, in _proto_data_received
    self._on_data_available(data)
  File "/path/to/my/venv/lib/python3.6/site-packages/pika/connection.py", line 2075, in _on_data_available
    self._process_frame(frame_value)
  File "/path/to/my/venv/lib/python3.6/site-packages/pika/connection.py", line 2224, in _process_frame
    if self._process_callbacks(frame_value):
  File "/path/to/my/venv/lib/python3.6/site-packages/pika/connection.py", line 2205, in _process_callbacks
    frame_value)  # Args
  File "/path/to/my/venv/lib/python3.6/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/path/to/my/venv/lib/python3.6/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/path/to/my/venv/lib/python3.6/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "asynchronous_consumer_example.py", line 229, in on_bindok
    self.start_consuming()
  File "asynchronous_consumer_example.py", line 244, in start_consuming
    callback=self.on_message)
TypeError: basic_consume() missing 1 required positional argument: 'on_message_callback'
```

Upon further investigation it looks like the ``pika`` v1.0 API changes some method signatures in the ``channel`` object and these changes have not been reflected in at least the two example files I was trying to run.

This merge request proposes changes that fix the two example files so they work with the new API exposed by ``pika``. The changes are relatively trivial.

Additional non-functional (i.e. style) changes were introduced after running ``yapf`` over the two modified files as requested in the *Code Formatting* section of this project's ``CONTRIBUTING.md`` guidelines file.

### CODE REVIEW

**Comment by claws** [comment]
The examples do not work with pika version 0.12.0 or 1.0.0.

**Comment by lukebakken** [comment]
@michaelklishin this is fine, we've switched other examples to the new API. @claws thanks for noticing this.

**Comment by claws** [comment]
I have removed the non-functional ``yapf`` related changes.

Should a seperate issue be raised on the ``CONTRIBUTING.md`` instructions that ask contributors to format their modified files with ``yapf``?

**Comment by claws** [comment]
> @claws please do that and use `stable` as the base branch for that pull request. The problem with those auto-formatters is that they change far more than the original intent of the pull requests.

As requested I have raised #1139, which targets the stable branch, to remove the line requesting contributors use yapf to format files they have changed.

**Comment by michaelklishin** [comment]
@lukebakken I'm not sure what's the status of this. Do we expect any more changes?

**Comment by lukebakken** [comment]
I am revisiting all of these stale PRs today.

**Comment by lukebakken** [comment]
Thank you!
