### ISSUE TITLE
URLParameters with SSL options not working

### ISSUE THREAD

**Issue by lukebakken** [pika/pika#1192]
https://groups.google.com/forum/#!topic/pika-python/IkpkRJVjxlg

When using pika==0.13.0, I'm getting an error when using URLParameters with SSL options.
It works fine on pika==0.12.0.

Minimal working example:

```
from pika import URLParameters
uri = "amqps://guest:guest@rabbitmq:5671/?ssl_options=%7B%27certfile%27%3A+%27%2Fapp%2Fcertificates%2Fclient%2Fclient_certificate.pem%27%2C+%27keyfile%27%3A+%27%2Fapp%2Fcertificates%2Fclient%2Fclient_key.pem%27%2C+%27ca_certs%27%3A+%27%2Fapp%2Fcertificates%2Fca%2Fca_certificate.pem%27%7D"
URLParameters(uri)
```

I'm defining SSL options as specified in documentation: https://pika.readthedocs.io/en/stable/examples/using_urlparameters.html

Error:
```
Traceback (most recent call last):
(...)
    url_parameters = URLParameters(uri)
  File "/Users/user/.virtualenvs/project/lib/python3.6/site-packages/pika/connection.py", line 849, in __init__
    set_value(value)
  File "/Users/user/.virtualenvs/project/lib/python3.6/site-packages/pika/connection.py", line 1008, in _set_url_ssl_options
    server_hostname=server_hostname)
TypeError: __init__() got an unexpected keyword argument 'context'
```

The error is happening here: https://github.com/pika/pika/blob/0.13.0/pika/connection.py#L1007.
`SSLOptions` class is not expecting keyword argument `context`, as can be confirmed in https://github.com/pika/pika/blob/0.13.0/pika/connection.py#L1039.

**Comment by lukebakken** [comment]
Fixed in #1193
